
//-------------------------------------------------------------------------
/**
 * Exception class for failed finds/removes in search
 * trees, hash tables, and list and tree iterators.
 * The serialVersionUID was generated by eclipse because
 * it was giving errors when it didn't exist.
 *
 * @author Samuel Turner <samt5>
 * @version 2017.09.16
 */
public class ItemNotFoundException extends RuntimeException {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constructs this ItemNotFoundException object.
     */
    public ItemNotFoundException()
    {
        super();
    }
}
